liip_imagine:
    filter_sets:
        news_announcements_today:
            quality: 95
            filters:
                thumbnail:
                    size: [400, 250]
                    mode: outbound
                strip: ~

        news_announcements_lists:
            quality: 95
            filters:
                relative_resize:
                    widen: 200

        news_announcements_lists_middle:
            quality: 95
            filters:
                relative_resize:
                    widen: 767

        news_announcements_lists_small:
            quality: 95
            filters:
                relative_resize:
                    widen: 414

        news_announcements_article:
            quality: 95
            filters:
                thumbnail:
                    size: [400, 250]
                    mode: outbound
                strip: ~
