navigation:
    menu_config:
        items:
            resource_library:
                label: 'oro.resourcelibrary.commerce_main_menu.label'
                uri: '/resource-library'
                extras:
                    position: 0
        tree:
            commerce_main_menu:
                children:
                    resource_library: ~

            commerce_footer_links:
                children:
                    information:
                        children:
                            resource_library: ~
