oro_literature_application_note:
    resource: "@OroResourceLibraryBundle/Controller/Frontend/LiteratureApplicationNoteController.php"
    type: annotation
    prefix: /literature-application-note
    options:
        frontend: true

oro_resource_library_media_kit:
    resource: "@OroResourceLibraryBundle/Controller/Frontend/MediaKitController.php"
    type: annotation
    prefix: /media-kit
    options:
        frontend: true

oro_safety_specification:
    resource: "@OroResourceLibraryBundle/Controller/Frontend/SafetySpecificationController.php"
    type: annotation
    prefix: /safety-specifications
    options:
        frontend: true

oro_resource_library_videos:
    resource: "@OroResourceLibraryBundle/Controller/Frontend/VideosController.php"
    type: annotation
    prefix: /videos
    options:
        frontend: true
