literature_application_note:
    resource: "@OroResourceLibraryBundle/Controller/Frontend/LiteratureApplicationNoteController.php"
    type: annotation
    prefix: /literature_and_application_notes
    options:
        frontend: true
