styles:
    inputs:
        - 'bundles/ororesourcelibrary/default/scss/variables/resource-library.scss'
        - 'bundles/ororesourcelibrary/default/scss/variables/resource-library-article.scss'
        - 'bundles/ororesourcelibrary/default/scss/variables/resource-library-datagrid.scss'
        - 'bundles/ororesourcelibrary/default/scss/variables/resource-library-kits.scss'
        - 'bundles/ororesourcelibrary/default/scss/variables/resource-library-literature.scss'
        - 'bundles/ororesourcelibrary/default/scss/variables/resource-library-newspost.scss'
        - 'bundles/ororesourcelibrary/default/scss/variables/resource-library-newsposts.scss'
        - 'bundles/ororesourcelibrary/default/scss/variables/resource-library-post.scss'
        - 'bundles/ororesourcelibrary/default/scss/variables/resource-library-posts.scss'
        - 'bundles/ororesourcelibrary/default/scss/variables/resource-library-section.scss'
        - 'bundles/ororesourcelibrary/default/scss/variables/resource-library-specifications.scss'

        - 'bundles/ororesourcelibrary/default/scss/components/resource-library.scss'
        - 'bundles/ororesourcelibrary/default/scss/components/resource-library-posts.scss'
        - 'bundles/ororesourcelibrary/default/scss/components/resource-library-post.scss'
        - 'bundles/ororesourcelibrary/default/scss/components/resource-library-article.scss'
        - 'bundles/ororesourcelibrary/default/scss/components/resource-library-section.scss'
        - 'bundles/ororesourcelibrary/default/scss/components/resource-library-datagrid.scss'
        - 'bundles/ororesourcelibrary/default/scss/components/resource-library-literature.scss'
        - 'bundles/ororesourcelibrary/default/scss/components/resource-library-specifications.scss'
        - 'bundles/ororesourcelibrary/default/scss/components/resource-library-kits.scss'
        - 'bundles/ororesourcelibrary/default/scss/components/resource-library-newspost.scss'
        - 'bundles/ororesourcelibrary/default/scss/components/resource-library-newsposts.scss'
