services:
    _defaults:
        public: true

    Oro\Bundle\ResourceLibraryBundle\Controller\Frontend\ResourceLibraryController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: 'container.service_subscriber', id: 'oro_resource_library.content_node_tree_resolver_no_cache', key: Oro\Bundle\WebCatalogBundle\ContentNodeUtils\ContentNodeTreeResolverInterface }

    Oro\Bundle\ResourceLibraryBundle\Controller\Frontend\LiteratureApplicationNoteController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\ResourceLibraryBundle\Controller\Frontend\SafetySpecificationController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: 'container.service_subscriber', id: 'oro_resource_library.content_node_tree_resolver_no_cache', key: Oro\Bundle\WebCatalogBundle\ContentNodeUtils\ContentNodeTreeResolverInterface }

    Oro\Bundle\ResourceLibraryBundle\Controller\Frontend\VideosController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: 'container.service_subscriber', id: 'oro_resource_library.content_node_tree_resolver_no_cache', key: Oro\Bundle\WebCatalogBundle\ContentNodeUtils\ContentNodeTreeResolverInterface }

    Oro\Bundle\ResourceLibraryBundle\Controller\Frontend\MediaKitController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: 'container.service_subscriber', id: 'oro_resource_library.content_node_tree_resolver_no_cache', key: Oro\Bundle\WebCatalogBundle\ContentNodeUtils\ContentNodeTreeResolverInterface }

    Oro\Bundle\ResourceLibraryBundle\Controller\Frontend\NewsAnnouncementsController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
