services:
    _defaults:
        public: true

    Oro\Bundle\ResourceLibraryBundle\Controller\Frontend\LiteratureApplicationNoteController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\ResourceLibraryBundle\Controller\Frontend\SafetySpecificationController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
