services:
    _defaults:
        public: true

    Oro\Bundle\ResourceLibraryBundle\Controller\Frontend\VideosController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
