services:
    oro_resource_library.content_variant_type.literature_application_note:
        class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\LiteratureApplicationNoteContentVariantType'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.content_variant_type.literature_application_note_file_collection:
        class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\LiteratureApplicationNoteFileCollectionContentVariantType'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.content_variant_type.media_kit_list:
        class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\MediaKitListContentVariantType'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.content_variant_type.media_kit_list_item:
        class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\MediaKitListItemContentVariantType'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.provider.literature_note_content_provider:
        class: 'Oro\Bundle\ResourceLibraryBundle\Provider\LiteratureNoteContentProvider'
        arguments:
            - '@oro_web_catalog.content_node_tree_resolver'
            - '@oro_scope.scope_manager'
            - '@oro_entity.doctrine_helper'

    Oro\Bundle\ResourceLibraryBundle\Provider\LiteratureNoteContentProvider:
        alias: oro_resource_library.provider.literature_note_content_provider

    oro_resource_library.block_type.section_list:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            -
                - setOptionsConfig
                -
                    -
                        items: {required: true}
                        exclude_item: ~
            - [setName, ['section_list']]
        tags:
            - { name: layout.block_type, alias: section_list }
