services:
    oro_resource_library.content_variant_type.resource_library:
        class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\ResourceLibraryContentVariantType'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.content_variant_type.literature_application_note:
        class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\LiteratureApplicationNoteContentVariantType'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.content_variant_type.literature_application_note_file_collection:
        class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\LiteratureApplicationNoteFileCollectionContentVariantType'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.content_variant_type.safety_specification_page:
        class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\SafetySpecificationPageContentVariantType'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.content_variant_type.safety_specification_section:
        class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\SafetySpecificationSectionContentVariantType'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.content_variant_type.safety_specification_file:
        class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\SafetySpecificationFileContentVariantType'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.content_variant_type.media_kit_list:
        class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\MediaKitListContentVariantType'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.content_variant_type.media_kit_list_item:
        class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\MediaKitListItemContentVariantType'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.content_variant_type.news_announcements:
      class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\NewsAnnouncementsContentVariantType'
      tags:
          - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.content_variant_type.news_announcements_article:
      class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\NewsAnnouncementsArticleContentVariantType'
      tags:
          - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.provider.literature_note_content_provider:
        class: 'Oro\Bundle\ResourceLibraryBundle\Provider\LiteratureNoteContentProvider'
        arguments:
            - '@oro_resource_library.content_node_tree_resolver_no_cache'
            - '@oro_scope.scope_manager'
            - '@oro_entity.doctrine_helper'

    Oro\Bundle\ResourceLibraryBundle\Provider\LiteratureNoteContentProvider:
        alias: oro_resource_library.provider.literature_note_content_provider

    oro_resource_library.content_variant_type.video_list:
        class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\VideoListContentVariantType'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.content_variant_type.video_list_section:
        class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\VideoListSectionContentVariantType'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.content_variant_type.video_list_section_item:
        class: 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\VideoListSectionItemContentVariantType'
        tags:
            - { name: oro_web_catalog.content_variant_type }

    oro_resource_library.event_listener.datagrid.video_list_section:
        class: 'Oro\Bundle\ResourceLibraryBundle\EventListener\VideoListSectionDatagridEventListener'
        arguments:
            - '@oro_web_catalog.content_node_provider'
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.pre.video-section-grid, method: onPreBuild }

    oro_resource_library.block_type.section_list:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            -
                - setOptionsConfig
                -
                    -
                        items: {required: true}
                        exclude_item: ~
            - [setName, ['section_list']]
        tags:
            - { name: layout.block_type, alias: section_list }

    oro_resource_library.block_type.content_variant_typed_child:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            -
                - setOptionsConfig
                -
                    -
                        items: {required: true}
                        requiredType: {required: true}
            - [setName, ['content_variant_typed_child']]
        tags:
            - { name: layout.block_type, alias: content_variant_typed_child }

    oro_resource_library.event_listener.datagrid.news_announcements_article:
        class: 'Oro\Bundle\ResourceLibraryBundle\EventListener\NewsAnnouncementsArticleDatagridEventListener'
        arguments:
            - '@oro_scope.scope_manager'
            - '@doctrine'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.pre.news-announcements-article-grid, method: onPreBuild }

    oro_resource_library.content_node_tree_resolver_no_cache:
        class: Oro\Bundle\WebCatalogBundle\ContentNodeUtils\ContentNodeTreeResolver
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_web_catalog.content_node_provider'
            - '@oro_scope.scope_manager'
            - '@oro_web_catalog.resolved_content_nodes_loader'
            - '@property_accessor'
