Oro\Bundle\ResourceLibraryBundle\Entity\Video:
    properties:
        shortDescription:
            - NotBlank: ~
        description:
            - NotBlank: ~
        link:
            - NotBlank: ~
            - Length:
                min: 1
                max: 255
            - Url:
                protocols: ['http', 'https']
